package com.cmx.myimrongyun.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cmx.myimrongyun.bean.MyMessage;
import com.cmx.myimrongyun.bean.UnReadMessage;

import com.cmx.myimrongyun.bean.MyMessageDao;
import com.cmx.myimrongyun.bean.UnReadMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myMessageDaoConfig;
    private final DaoConfig unReadMessageDaoConfig;

    private final MyMessageDao myMessageDao;
    private final UnReadMessageDao unReadMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myMessageDaoConfig = daoConfigMap.get(MyMessageDao.class).clone();
        myMessageDaoConfig.initIdentityScope(type);

        unReadMessageDaoConfig = daoConfigMap.get(UnReadMessageDao.class).clone();
        unReadMessageDaoConfig.initIdentityScope(type);

        myMessageDao = new MyMessageDao(myMessageDaoConfig, this);
        unReadMessageDao = new UnReadMessageDao(unReadMessageDaoConfig, this);

        registerDao(MyMessage.class, myMessageDao);
        registerDao(UnReadMessage.class, unReadMessageDao);
    }
    
    public void clear() {
        myMessageDaoConfig.clearIdentityScope();
        unReadMessageDaoConfig.clearIdentityScope();
    }

    public MyMessageDao getMyMessageDao() {
        return myMessageDao;
    }

    public UnReadMessageDao getUnReadMessageDao() {
        return unReadMessageDao;
    }

}
